jobs:
  lint_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm lint:package

name: Lint Package

on:
  pull_request: ~
  push:
    branches:
      - main
